[package]
name = "timer_scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
# Async runtime
tokio = { version = "1.42", features = ["full"] }

# HTTP server
hyper = { version = "0.14", features = ["full"] }
axum = "0.7"

# Logging & tracing
tracing = "0.1.40"
tracing-subscriber = "0.3"

# JSON serialization
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.106"

# SQLite database
rusqlite = { version = "0.29", features = ["bundled"] }
r2d2 = "0.8"
r2d2_sqlite = "0.22"

argon2 = "0.5"  # for password hashing
uuid = { version = "1.4", features = ["v4"] }