### Test login with default admin
POST http://127.0.0.1:8080/login
Content-Type: application/json

{
  "user_name": "admin",
  "password": "admin"
}

### Test login with wrong password
POST http://127.0.0.1:8080/login
Content-Type: application/json

{
  "user_name": "admin",
  "password": "wrongpass"
}

### Test login with non-existing user
POST http://127.0.0.1:8080/login
Content-Type: application/json

{
  "user_name": "unknown",
  "password": "1234"
}

### Create an app
POST http://127.0.0.1:8080/app
Content-Type: application/json

{
  "name": "my-app"
}

### Delete an app by id
DELETE http://127.0.0.1:8080/app/1

### Get list of apps
GET http://127.0.0.1:8080/apps